# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MemoryAllocatorsCore_config = debug

else ifeq ($(config),release)
  MemoryAllocatorsCore_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := MemoryAllocatorsCore

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

MemoryAllocatorsCore:
ifneq (,$(MemoryAllocatorsCore_config))
	@echo "==== Building MemoryAllocatorsCore ($(MemoryAllocatorsCore_config)) ===="
	@${MAKE} --no-print-directory -C . -f MemoryAllocatorsCore.make config=$(MemoryAllocatorsCore_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f MemoryAllocatorsCore.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MemoryAllocatorsCore"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"